[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "6H8y6VtLKBxo5UdnSJWfpXpn6tZc3gDAmfudCe1srifw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rodriguezpatricio/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
